### ISSUE TITLE
main ability not showing up sometimes?

### ISSUE THREAD

**Issue by Zagorsek** [SirBraneDamuj/mustadio#25]
never noticed this before but sometimes the main ability is missing from the list, sometimes its there

https://www.mustad.io/tournament_1584670833549/white/black

![image](https://user-images.githubusercontent.com/61329633/77131526-4498e000-6a32-11ea-9aac-6d987114d990.png)

**Comment by SirBraneDamuj** [comment]
I know why it's happening. They started appearing in `infoability.txt` in the dump. I use their absence from that list as a way of determining if the ability is an active or not. Any of the ones with a ` ` in the name will continue to show up because `infoability.txt` doesn't use spaces.

**Comment by SirBraneDamuj** [comment]
Fixed. Thanks for bringing it to my attention. I've been distracted with PoE lately so haven't been paying much attention :)
