### ISSUE TITLE
maps sometimes out of order

### ISSUE THREAD

**Issue by Zagorsek** [SirBraneDamuj/mustadio#3]
https://www.mustad.io/tournament_1582335058217/red/blue

tourney map listing sometimes gets out of order.

2nd and 3rd fight maps are swapped.
4th and 5th fight maps are swapped.
![image](https://user-images.githubusercontent.com/61329633/75084281-2e5c3a80-54ed-11ea-9a53-72838a81ae1c.png)

actual map order should be

![image](https://user-images.githubusercontent.com/61329633/75084354-9874df80-54ed-11ea-83c4-4d12a62cfd83.png)

**Comment by SirBraneDamuj** [comment]
I think I know the fix for this and it should be pretty straightforward. I'm not ordering the maps query so I'm just counting on the natural order from the db being correct.

**Comment by SirBraneDamuj** [comment]
I've pushed a fix for this to master and it should get deployed to staging soon. I don't think it'll be a destructive change so I'll push it to prod soon. Let me know if you observe any other tournaments that load maps improperly.
